services:
  postgres_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432" # Different port to avoid collisions with main DB
    networks:
      - test-network

  redis_test:
    image: redis:latest
    ports:
      - "6379:6379" # Redis for testing, standard
    networks:
      - test-network

  app_test:
    build:
      context: .
    environment:
      DB_HOST: postgres_test
      DB_PORT: 5432
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_DATABASE: test_db
      REDIS_HOST: redis_test
      REDIS_PORT: 6379
    depends_on:
      - postgres_test
      - redis_test
    networks:
      - test-network
    command: npm run test # This will run the test suite

networks:
  test-network:
