// import { test } from '@japa/runner'
// import ActivityLog from '#models/activity_log'
// import User from '#models/user'
// import mock from 'mock-fs'
// import { faker } from '@faker-js/faker'
// import fs from 'fs'
// import path from 'path'